### ISSUE TITLE
Use of Polymer and material design in the code samples

### ISSUE THREAD

**Issue by jdrew1303** [google/google-apps-script-samples#15]
Hey, first off, thanks for the sample code. They were really helpful :+1: 

In the guides for publishing an add on there are general rules:
![image](https://cloud.githubusercontent.com/assets/2535432/14281710/99c36b4a-fb32-11e5-97d9-afc858ecad6e.png)

In the demo scripts supplied you use both. From the Readme.md:
![image](https://cloud.githubusercontent.com/assets/2535432/14283144/dfa34b10-fb39-11e5-89d4-08c0519dc3db.png)

Is it not strictly enforced, or that this is a decision that's changing in the future as more of the Google apps move towards Material design? The reason I ask is because I've been building a Sheets sidebar addon using ionic components for the UI and I'm starting to wonder if it will be accepted given the UI guide? 

eg (Note this was just to test if would could get ionics main components running and isn't the app, the add in does salesforce reporting integration, query editing simillar to pivot tables, etc):
![ionic_in_google_sheets_full_demo](https://cloud.githubusercontent.com/assets/2535432/14281947/e2cf929a-fb33-11e5-8f7f-570fca6d1c3d.gif)

**Comment by ryan-devrel** [comment]
The restriction against Material Design in add-ons has been lessened. The main point of that restriction was to prevent add-ons with designs that clashed or were too different from the design of the Docs / Sheets editors themselves. So long as it doesn't look and operate poorly, you should be able to have the add-on pass review.

**Comment by jdrew1303** [comment]
Thanks @ryan-devrel. Sorry, I know this probably wasn't the best place to ask so I appreciate the help.

**Comment by iacomus** [comment]
Hi @ryan-devrel I have a similar question related to this. We're considering using [Salesforce Lightening Out](https://releasenotes.docs.salesforce.com/en-us/spring16/release-notes/rn_lightning_out.htm) components in our Google App Script add-on. Before we head down this road, would these components pass the style guidelines? Also, is there any reason to believe that embedding these components would cause us issue passing security review for Google App Script? Thanks.

**Comment by ryan-devrel** [comment]
iacomus, I'm not familiar enough with Lightning to say for certain -- it will largely depend on what exactly you are trying to do. I don't see any immediate issue with using Lightning, but the reviewer who reviews your add-on may have a different opinion.
